// src/components/WeatherCard/index.tsx
import * as C from "./styles";
import ArrowUp from "../../images/icons/upload.png";
import ArrowDown from "../../images/icons/download.png";
import Raindrop from "../../images/icons/raindrop-close-up.png";
import Umbrella from "../../images/icons/protection-symbol-of-opened-umbrella-silhouette-under-raindrops.png"
import { Weather } from "../../types/Weather";
import { formatDate } from "../../helpers/formatDate";
import { celsiusToFahrenheit } from "../../helpers/celsiusToFahrenheit";
import { useEffect, useState } from "react";
import { mmToInch } from "../../helpers/mmToInch";

export const WeatherCard = ({ item }: { item: Weather }) => {
    const [min, setMin] = useState('');
    const [max, setMax] = useState('');
    const [probability, setProbability] = useState('');

    useEffect(() => {
        setMin(item.temperature.min + "°C");
        setMax(item.temperature.max + "°C");
        setProbability(item.rain.probability + "mm");
    }, []);

    function handleClick(value: string) {
        if (value.includes("°C")) {
            value.includes("max") && setMax(celsiusToFahrenheit(value.replace("max", "")));
            value.includes("min") && setMin(celsiusToFahrenheit(value.replace("min", "")));
        }
        if (value.includes("°F")) {
            value.includes("max") && setMax(item.temperature.max + "°C");
            value.includes("min") && setMin(item.temperature.min + "°C");
        }
        if (value.includes("prob")) {
            value.includes("mm") && setProbability(mmToInch(value.replace("mm", "")));
            value.includes("inch") && setProbability(item.rain.probability + "mm");
        }
    }

    return (
        <C.Container>
            <C.Info>
                <C.Date>{formatDate(item.date)}</C.Date>
                <C.Resume>{item.text}</C.Resume>
            </C.Info>
            <C.Statistics>
                <C.Max onClick={() => handleClick(max + "max")}>
                    <C.Icon
                        src={ArrowUp}
                        alt="Arrow up icon"
                    />
                    <C.Text textColor="#0478BD">{max}</C.Text>
                </C.Max>
                <C.Min onClick={() => handleClick(min + "min")}>
                    <C.Icon
                        src={ArrowDown}
                        alt="Arrow down icon"
                    />
                    <C.Text textColor="#C93838">{min}</C.Text>
                </C.Min>
                <C.Probability onClick={() => handleClick(probability + "prob")}>
                    <C.Icon
                        src={Raindrop}
                        alt="Raindrop icon"
                    />
                    <C.Text textColor="#000">{probability}</C.Text>
                </C.Probability>
                <C.Precipitation>
                    <C.Icon
                        src={Umbrella}
                        alt="Umbrella icon"
                    />
                    <C.Text textColor="#000">{item.rain.precipitation}%</C.Text>
                </C.Precipitation>
            </C.Statistics>
        </C.Container>
    );
}

// resources/assets/js/components/WeatherCard.vue
<template>
    <div class="panel panel-default">
        <div class="panel-body">
            <span class="text-muted">{{ formattedDate }}</span>

            <div class="row">
                <div class="col-xs-6">
                    <div class="card-forecast-statistics">
                        <img src="/images/icons/raindrop-close-up.png" alt="">
                        {{ weather.rain.precipitation }}mm
                    </div>

                    <div class="card-forecast-statistics">
                        <img src="/images/icons/protection-symbol-of-opened-umbrella-silhouette-under-raindrops.png" alt="">
                        {{ weather.rain.probability }}%
                    </div>
                </div>
                <div class="col-xs-6">
                    <div class="card-temperature">
                        <i class="glyphicon glyphicon-arrow-up text-warning"></i> <span>{{ weather.temperature.max }}ºC</span>
                        <br>
                        <i class="glyphicon glyphicon-arrow-down text-info"></i> <span>{{ weather.temperature.min }}ºC</span>
                    </div>
                </div>
            </div>

            <hr>

            <p>{{ weather.text }}</p>
        </div>
    </div>
</template>

<script>
export default {
    props: [ "weather" ],

    computed: {
        formattedDate() {
            let date = new Date(this.weather.date)
            return `${date.getUTCDate()}/${date.getUTCMonth() + 1}/${date.getUTCFullYear()}`
        }
    }
}
</script>

<style lang="scss">
    .card-forecast-statistics {
        display: inline-block;
        width: 75px;
        padding: 10px;
        margin-top: 28px;
        left: auto;
        text-align: center;
    }

    .card-temperature {
        width: 100px;
        display: block;
        position: relative;
        margin-left: auto;
        margin-right: auto;
        span { font-size: 2.5em; }
    }
</style>
