// src/components/WeatherCard.jsx
import React, { Component } from 'react';
import { Col } from 'react-bootstrap';

export default class WeatherCard extends Component {
  render() {
    const { date, text, temperature, rain } = this.props.weather
    return (
      <Col xs={12} sm={6} md={4}>
        <div className="weather-card">
        	<div className="card-header">
  	      	<h6>{date}</h6>
  	      	<p><small>{text}</small></p>
        	</div>
        	<div className="subcard">
        		<div>
        			<div>
  	      			<img src="imgs/icons/upload.png"/>
  	      			<span className="color-blue">{temperature.max} ºC</span>
        			</div>
        			<div>
  	      			<img src="imgs/icons/download.png"/>
  	      			<span className="color-red">{temperature.min} ºC</span>
        			</div>
        		</div>
        		<div>
        			<div>
  	      			<img src="imgs/icons/raindrop-close-up.png"/>
  	      			<span>{rain.precipitation}mm</span>
        			</div>
        			<div>
  	      			<img src="imgs/icons/protection-symbol-of-opened-umbrella-silhouette-under-raindrops.png"/>
  	      			<span>{rain.probability}%</span>
        			</div>
        		</div>
        	</div>
        </div>
      </Col>
    );
  }
}

// resources/assets/js/components/WeatherCard.vue
<template>
    <div class="panel panel-default">
        <div class="panel-body">
            <span class="text-muted">{{ formattedDate }}</span>

            <div class="row">
                <div class="col-xs-6">
                    <div class="card-forecast-statistics">
                        <img src="/images/icons/raindrop-close-up.png" alt="">
                        {{ weather.rain.precipitation }}mm
                    </div>

                    <div class="card-forecast-statistics">
                        <img src="/images/icons/protection-symbol-of-opened-umbrella-silhouette-under-raindrops.png" alt="">
                        {{ weather.rain.probability }}%
                    </div>
                </div>
                <div class="col-xs-6">
                    <div class="card-temperature">
                        <i class="glyphicon glyphicon-arrow-up text-warning"></i> <span>{{ weather.temperature.max }}ºC</span>
                        <br>
                        <i class="glyphicon glyphicon-arrow-down text-info"></i> <span>{{ weather.temperature.min }}ºC</span>
                    </div>
                </div>
            </div>

            <hr>

            <p>{{ weather.text }}</p>
        </div>
    </div>
</template>

<script>
export default {
    props: [ "weather" ],

    computed: {
        formattedDate() {
            let date = new Date(this.weather.date)
            return `${date.getUTCDate()}/${date.getUTCMonth() + 1}/${date.getUTCFullYear()}`
        }
    }
}
</script>

<style lang="scss">
    .card-forecast-statistics {
        display: inline-block;
        width: 75px;
        padding: 10px;
        margin-top: 28px;
        left: auto;
        text-align: center;
    }

    .card-temperature {
        width: 100px;
        display: block;
        position: relative;
        margin-left: auto;
        margin-right: auto;
        span { font-size: 2.5em; }
    }
</style>
