// src/components/header/index.tsx
import React from 'react';

import { Container } from './styles';

import logo from '../../images/logo-white.png';
import search from '../../images/icons/search.svg';

const Header: React.FC = () => {
  return (
    <Container>
      <img className="logo" src={logo} alt="climatempo logo" />
      <img className="search" src={search} alt="climatempo logo" />
    </Container>
  );
};

export default Header;

// apps/webapp/src/app/header/header.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'climatempo-header',
    templateUrl: './header.component.html'
})
export class HeaderComponent {
    constructor() {}
}

<nav class="navbar navbar-dark bg-primary">
    <a class="navbar-brand" href="#">
        <img src="./assets/logo-white.png" class="logo" />
    </a>
</nav>
