// src/components/Header.jsx
import React, { Component } from 'react';
import { Navbar } from 'react-bootstrap';

export default class Header extends Component {
  render() {
    return (
      <Navbar>
		    <Navbar.Header>
		      <Navbar.Brand>
		        <img src="imgs/logo-white.png" />
		      </Navbar.Brand>
		    </Navbar.Header>
		  </Navbar>
    );
  }
}

// apps/webapp/src/app/header/header.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'climatempo-header',
    templateUrl: './header.component.html'
})
export class HeaderComponent {
    constructor() {}
}

<nav class="navbar navbar-dark bg-primary">
    <a class="navbar-brand" href="#">
        <img src="./assets/logo-white.png" class="logo" />
    </a>
</nav>
