// climatempo/src/components/Card/Card.tsx
import React from "react";
import styled from "styled-components";
import max from "../../assets/icons/max.png";
import min from "../../assets/icons/min.png";
import probabilityIcon from "../../assets/icons/probability.png";
import precipitationIcon from "../../assets/icons/precipitation.png";

type TypeCard = {
  date: string;
  text: string;
  temperaturaMin: number;
  temperaturaMax: number;
  probability: number;
  precipitation: number;
};

function Card({
  date,
  text,
  temperaturaMin,
  temperaturaMax,
  probability,
  precipitation,
}: TypeCard) {
  return (
    <Container>
      <Header>
        <Date>{date}</Date>
        <Description>{text}</Description>
      </Header>
      <Body>
        <Column>
          <Row>
            <Icon src={max} alt="max" />
            <Row>
              <Number>{temperaturaMax}</Number>
              <Number>°C</Number>
            </Row>
          </Row>
          <Row>
            <Icon src={probabilityIcon} alt="probability" />
            <Row>
              <Number>{precipitation}</Number>
              <Number>mm</Number>
            </Row>
          </Row>
        </Column>
        <Column>
          <Row>
            <Icon src={min} alt="min" />
            <Row>
              <Number>{temperaturaMin}</Number>
              <Number>°C</Number>
            </Row>
          </Row>
          <Row>
            <Icon src={precipitationIcon} alt="precipitation" />
            <Row>
              <Number>{probability}</Number>
              <Number>%</Number>
            </Row>
          </Row>
        </Column>
      </Body>
    </Container>
  );
}

const Container = styled.div`
  width: 346px;
  height: 230px;
  background: #d9d9d9;
  border-radius: 20px;
  display: flex;
  flex-direction: column;

  @media (max-width: 888px) {
    width: 346px;
    height: 230px;
  }

  @media (max-width: 468px) {
    width: 274px;
    height: 220px;
  }
`;

const Header = styled.div`
  width: 346px;
  height: 80px;
  background: #047ab2;
  border-radius: 20px;
  display: flex;
  flex-direction: column;
  align-items: center;

  @media (max-width: 888px) {
    width: 346px;
    height: 80px;
  }

  @media (max-width: 468px) {
    width: 274px;
    height: 160px;
  }
`;

const Date = styled.div`
  margin-top: 10px;
  margin-left: 10px;
  font-family: "Roboto", sans-serif;
  font-style: normal;
  font-weight: 400;
  font-size: 18px;
  line-height: 24px;
  color: #ffffff;

  @media (max-width: 888px) {
    font-size: 18px;
  }

  @media (max-width: 468px) {
    font-size: 16px;
  }
`;

const Description = styled.p`
  width: 80%;
  margin-bottom: 10px;
  margin-left: 10px;
  font-family: "Roboto", sans-serif;
  font-style: normal;
  font-weight: 400;
  font-size: 13px;
  line-height: 14px;
  color: #ffffff;
`;

const Body = styled.div`
  display: flex;
  flex-direction: row;
`;

const Column = styled.div`
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  width: 50%;
`;

const Icon = styled.img`
  width: 25px;
  height: 25px;

  @media (max-width: 868px) {
    width: 20px;
    height: 20px;
  }

  @media (max-width: 468px) {
    width: 20px;
    height: 20px;
  }
`;

const Row = styled.div`
  width: 80px;
  display: flex;
  flex-direction: row;
  justify-content: center;
  align-items: center;
`;

const Number = styled.p`
  margin-left: 10px;
  font-family: "Roboto", sans-serif;
  font-style: normal;
  font-weight: 400;
  font-size: 24px;
  line-height: 29px;
  color: #000000;

  @media (max-width: 868px) {
    font-size: 18px;
  }

  @media (max-width: 468px) {
    font-size: 18px;
  }
`;

export default Card;

// components/Card.vue
<template lang="html">
  <b-card
    no-body
    style="width: 100%"
  >
    <template v-slot:header>
      <h6>{{ date }}</h6>
      <p>{{ text }}</p>
    </template>

    <b-card-body class="">
      <div class="row">
        <div class="col-6">
          <img src="/images/icons/upload.png" alt="">
          <span class="text-primary">{{ max }}</span>
        </div>
        <div class="col-6">
          <img src="/images/icons/download.png" alt="">
          <span class="text-danger">{{ min }}</span>
        </div>
        <div class="col-6 pt-3">
          <img src="/images/icons/raindrop-close-up.png" alt="">
          <span class="text-dark">{{ water }}</span>
        </div>
        <div class="col-6 pt-3">
          <img src="/images/icons/protection-symbol-of-opened-umbrella-silhouette-under-raindrops.png" alt="">
          <span class="text-dark">{{ rain }}</span>
        </div>
      </div>
    </b-card-body>
  </b-card>
</template>

<script>
export default {
}
</script>

<style lang="css" scoped>
.card-body {
  padding: 10px;
}
.row {
  margin: 0px;
}
.col-6 {
  display: flex;
  align-items: center;
  padding: 3px;
  padding-top: 0px;
}
.col-6 span {
  width: 100%;
  text-align: center;
  font-size: 22px;
}
p {
  font-size: 12px;
  margin-bottom: 0px;
}
h6 {
  font-weight: bold;
}
.text-primary {
  color: #127fc0;
}
.text-danger {
  color: #ca3e3e;
}
.text-dark {
  color: #000;
}
</style>
