// components/Card.vue
<template lang="html">
  <b-card
    no-body
    style="width: 100%"
  >
    <template v-slot:header>
      <h6>{{ date }}</h6>
      <p>{{ text }}</p>
    </template>

    <b-card-body class="">
      <div class="row">
        <div class="col-6">
          <img src="/images/icons/upload.png" alt="">
          <span class="text-primary">{{ max }}</span>
        </div>
        <div class="col-6">
          <img src="/images/icons/download.png" alt="">
          <span class="text-danger">{{ min }}</span>
        </div>
        <div class="col-6 pt-3">
          <img src="/images/icons/raindrop-close-up.png" alt="">
          <span class="text-dark">{{ water }}</span>
        </div>
        <div class="col-6 pt-3">
          <img src="/images/icons/protection-symbol-of-opened-umbrella-silhouette-under-raindrops.png" alt="">
          <span class="text-dark">{{ rain }}</span>
        </div>
      </div>
    </b-card-body>
  </b-card>
</template>

<script>
export default {
}
</script>

<style lang="css" scoped>
.card-body {
  padding: 10px;
}
.row {
  margin: 0px;
}
.col-6 {
  display: flex;
  align-items: center;
  padding: 3px;
  padding-top: 0px;
}
.col-6 span {
  width: 100%;
  text-align: center;
  font-size: 22px;
}
p {
  font-size: 12px;
  margin-bottom: 0px;
}
h6 {
  font-weight: bold;
}
.text-primary {
  color: #127fc0;
}
.text-danger {
  color: #ca3e3e;
}
.text-dark {
  color: #000;
}
</style>

// src/components/Card/index.jsx
import React from 'react';
import './styles.scss';
import up from '../../assets/images/icons/upload.png';
import down from '../../assets/images/icons/download.png';
import rain from '../../assets/images/icons/protection-symbol-of-opened-umbrella-silhouette-under-raindrops.png';
import temp from '../../assets/images/icons/raindrop-close-up.png';

import Search from '../Search';
import { connect } from 'react-redux';
import { bindActionCreators } from 'redux';
import { searchWeather } from '../../store/actions';

const Card = (props) => {
  return (
    <>
      <Search onSearch={(v) => props.searchWeather(v)} />
      {props.search.map((elem) => (
        <h1>Previsão para {`${elem.locale.name} - ${elem.locale.state}`}</h1>
      ))}
      {props.search.map((item) =>
        item.weather.map((elem) => (
          <section className="bgCard" key={elem.date}>
            <section className="bgCard-header">
              <h2>{elem.date}</h2>
              <p>{elem.text}</p>
            </section>
            <section className="bgCard-content">
              <section className="bgCard-content_temp">
                <table>
                  <tr>
                    <td>
                      <img src={up} title="" alt="" />
                    </td>
                    <td className="colorTemp">{elem.temperature.max}°C</td>
                  </tr>
                  <tr>
                    <td>
                      <img src={temp} title="" alt="" />
                    </td>
                    <td>{elem.rain.probability}mm</td>
                  </tr>
                </table>
              </section>
              <section className="bgCard-content_rain">
                <table>
                  <tr>
                    <td>
                      <img src={down} title="" alt="" />
                    </td>
                    <td className="colorRain">{elem.temperature.min}°C</td>
                  </tr>
                  <tr>
                    <td>
                      <img src={rain} title="" alt="" />
                    </td>
                    <td>{elem.rain.precipitation}%</td>
                  </tr>
                </table>
              </section>
            </section>
          </section>
        )),
      )}
    </>
  );
};

const mapStateToProps = (state) => ({
  app: state.app,
  search: state.weather.search,
});

const mapDispatchToProps = (dispatch) =>
  bindActionCreators(
    {
      searchWeather,
    },
    dispatch,
  );

export default connect(mapStateToProps, mapDispatchToProps)(Card);
