// resources/reactjs/src/components/Header/Header.js
import React, {Component} from 'react';
import Logo from '../../assets/images/logo.png';

// The header component
class Header extends Component {
  render(){
    return (
      <header className='header background-primary flex flex-align-center flex-justify-center'>
      <img className='logo' src={Logo} /> 
      </header>
    );
  }
}

export default Header;

// frontend/climatempo/src/app/layout/header/header.component.ts
import { Component } from '@angular/core';
/**
 * @author Gabriel
 */
@Component({
  selector: 'app-header',
  templateUrl: './header.component.html'
})
export class HeaderComponent {

  constructor() {
  }
}

<div class="topo" fxLayout="column" fxLayoutAlign="center center">
    <img class="logo" fxLayoutAlign="center center" src='assets/images/logo-white.png'>
</div>
