// components/WeatherCard.vue
<template lang="html">
  <b-card
    no-body
    style="width: 100%"
  >
    <template v-slot:header>
      <h6>{{ date }}</h6>
      <p>{{ text }}</p>
    </template>

    <b-card-body>
      <div class="row">
        <div class="col-6">
          <img src="/images/icons/upload.png" alt="">
          <span class="text-primary">{{ max }}ºC</span>
        </div>
        <div class="col-6">
          <img src="/images/icons/download.png" alt="">
          <span class="text-danger">{{ min }}ºC</span>
        </div>
        <div class="col-6 pt-3">
          <img src="/images/icons/raindrop-close-up.png" alt="">
          <span class="text-dark">{{ precipitation }}mm</span>
        </div>
        <div class="col-6 pt-3">
          <img src="/images/icons/protection-symbol-of-opened-umbrella-silhouette-under-raindrops.png" alt="">
          <span class="text-dark">{{ probability }}%</span>
        </div>
      </div>
    </b-card-body>
  </b-card>
</template>

<script>
export default {
  props: {
    max: {
      type: [String, Number],
      default: ''
    },
    min: {
      type: [String, Number],
      default: ''
    },
    probability: {
      type: [String, Number],
      default: ''
    },
    precipitation: {
      type: [String, Number],
      default: ''
    },
    date: {
      type: String,
      default: ''
    },
    text: {
      type: String,
      default: ''
    }
  }
}
</script>

<style lang="css" scoped>
.card-body {
  padding: 10px;
}
.row {
  margin: 0px;
}
.col-6 {
  display: flex;
  align-items: center;
  padding: 3px;
  padding-top: 0px;
}
.col-6 span {
  width: 100%;
  text-align: center;
  font-size: 22px;
}
p {
  font-size: 12px;
  margin-bottom: 0px;
}
h6 {
  font-weight: bold;
}
.text-primary {
  color: #127fc0;
}
.text-danger {
  color: #ca3e3e;
}
.text-dark {
  color: #000;
}
</style>

// app/frontend/src/Components/WeatherCard.jsx
import { useContext } from 'react';

import context from '../Context/context';

import UmbrelaPng from '../images/icons/protection-symbol-of-opened-umbrella-silhouette-under-raindrops.png';
import RainDropPng from '../images/icons/raindrop-close-up.png';
import DownloadPng from '../images/icons/download.png';
import UploadPng from '../images/icons/upload.png';

export default function WeatherCard({ toggle }) {
  const { weathers } = useContext(context);

  const calculatesToFahrenheit = (temperature) => {
    const fahrenheitTemperature = temperature * 1.8 + 32;
    return fahrenheitTemperature.toFixed(1);
  };

  return (
    <div className="flex flex-col items-center mt-5">
      {weathers[0]?.date && weathers.map((weather, index) => (
        <div
          className="flex flex-col mb-5 p-2 h-56 border w-4/5"
          key={index + weather.date}
        >
          <p className="mb-1 ml-2 text-xl">
            {weather.date.split('-').reverse().join('/')}
          </p>

          <p className="text-md ml-2 mb-2">{weather.text}</p>

          {/* container of max & min temperature and rain probability & rain precipitation */}
          <section className='flex flex-col gap-4 m-auto w-full'>
            {/* max and min temperature */}
            <article className="flex justify-around">
              <div className="flex gap-1 items-center">
                <img src={UploadPng} alt="" />
                <p className="text-lg text-blue-500">
                  {toggle === 'C'
                    ? weather.temperature.max
                    : calculatesToFahrenheit(weather.temperature.max)}{' '}
                  {toggle} °
                </p>
              </div>
              <div className="flex gap-1 items-center">
                <img src={DownloadPng} alt="" />
                <p className="text-lg text-red-600">
                  {toggle === 'C'
                    ? weather.temperature.min
                    : calculatesToFahrenheit(weather.temperature.min)}{' '}
                  {toggle} °
                </p>
              </div>
            </article>

            {/* rain probabilty and rain precipitaion */}
            <article className="flex justify-around">
              <div className="flex gap-1 items-center">
                <img src={UmbrelaPng} alt="umbrela under rain" width={35} />
                <p className="text-lg">{weather.rain.probability}%</p>
              </div>

              <div className="flex gap-1 items-center">
                <img src={RainDropPng} alt="rain drop" width={30} />
                <p className="text-lg">{weather.rain.precipitation}mm</p>
              </div>
            </article>
          </section>
        </div>
      ))}
    </div>
  );
}
