// apps/webapp/src/app/header/header.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'climatempo-header',
    templateUrl: './header.component.html'
})
export class HeaderComponent {
    constructor() {}
}

<nav class="navbar navbar-dark bg-primary">
    <a class="navbar-brand" href="#">
        <img src="./assets/logo-white.png" class="logo" />
    </a>
</nav>

// frontend/src/components/Header/index.jsx
import React from 'react';

import logo from '../../assets/logo-white.png';
import styles from './header.module.css';

export default function Header() {
  return (
    <header className={styles.container}>
      <div>
        <img src={logo} alt="climatempo logo" />
      </div>
    </header>
  );
}
